import fs from "node:fs/promises";
import path from "node:path";
import { createNextRunDir } from "./runs.js";
import { writeJsonAtomic } from "./fs-utils.js";
import { findLatestApprovedRun } from "./state.js";
import { runPhase1 } from "./phase1.js";
import { runPhase2 } from "./phase2.js";
import { runPhase3 } from "./phase3.js";
import { runPhase4 } from "./phase4.js";
import { runPhase5 } from "./phase5.js";
import { runPhase6 } from "./phase6.js";
import { runPhase7 } from "./phase7.js";
import { runPhase8 } from "./phase8.js";
import { runPhase9 } from "./phase9.js";
import { runPhase10 } from "./phase10.js";

type RunPhaseArgs = { phase: number };

async function failClosed(runDir: string, err: unknown): Promise<never> {
  const message =
    err instanceof Error ? err.message : typeof err === "string" ? err : "Error";
  await writeJsonAtomic(path.join(runDir, "failure_report.json"), {
    ok: false,
    error: message,
  });
  // Ensure missing_md_report.json always exists, even on failure.
  const missingMdPath = path.join(runDir, "missing_md_report.json");
  try {
    await fs.stat(missingMdPath);
  } catch {
    await writeJsonAtomic(missingMdPath, {
      generatedAt: new Date().toISOString(),
      expected: [],
      missing: [],
      note: "Generated by fail-closed handler; phase did not produce missing_md_report.json.",
    });
  }
  await fs.writeFile(
    path.join(runDir, "root_cause.md"),
    `# Root Cause\n\n${message}\n`,
    "utf8",
  );
  await fs.writeFile(
    path.join(runDir, "recommendation.md"),
    `# Recommendation\n\nFix the root cause and re-run this phase into a new run folder.\n`,
    "utf8",
  );
  process.exit(1);
}

export async function runPhase({ phase }: RunPhaseArgs): Promise<void> {
  const run = await createNextRunDir(phase);

  try {
    // Pin Phase 1 canonical inventory as the only canonical path source for later phases.
    if (phase > 1) {
      const approvedPhase1 = await findLatestApprovedRun(1);
      if (!approvedPhase1) {
        throw new Error(
          "No approved Phase 1 run found (approval.json missing). Cannot proceed.",
        );
      }
      const phase1Inventory = path.join(
        approvedPhase1.runDir,
        "canonical_inventory.json",
      );
      const inventoryText = await fs.readFile(phase1Inventory, "utf8");
      await fs.writeFile(
        path.join(run.runDir, "canonical_inventory.lock.json"),
        inventoryText,
        "utf8",
      );
    }

    if (phase === 1) {
      await runPhase1({ runDir: run.runDir });
    } else if (phase === 2) {
      await runPhase2({ runDir: run.runDir });
    } else if (phase === 3) {
      await runPhase3({ runDir: run.runDir });
    } else if (phase === 4) {
      await runPhase4({ runDir: run.runDir });
    } else if (phase === 5) {
      await runPhase5({ runDir: run.runDir });
    } else if (phase === 6) {
      await runPhase6({ runDir: run.runDir });
    } else if (phase === 7) {
      await runPhase7({ runDir: run.runDir });
    } else if (phase === 8) {
      await runPhase8({ runDir: run.runDir });
    } else if (phase === 9) {
      await runPhase9({ runDir: run.runDir });
    } else if (phase === 10) {
      await runPhase10({ runDir: run.runDir });
    } else {
      throw new Error(
        `Phase ${phase} not implemented yet in the runner.`,
      );
    }

    // Minimum required evidence for every phase run.
    // (Phase implementations must overwrite these with real content.)
    const requiredFiles = ["missing_md_report.json", "validation.json", "test_results.json"];
    for (const f of requiredFiles) {
      const p = path.join(run.runDir, f);
      await fs.stat(p);
    }
  } catch (err) {
    await failClosed(run.runDir, err);
  }
}
