import fs from "node:fs/promises";
import path from "node:path";
import { fileExists } from "./fs-utils.js";
import { CONTENT_REGISTRIES_ROOT } from "./paths.js";
import { findLatestApprovedRun } from "./state.js";

type RegistryEntry = {
  slug: string;
  markdownPath: string;
};

async function loadRegistryEntries(registryFile: string): Promise<RegistryEntry[]> {
  // Registry files are TypeScript, but the governed runner executes under plain node.
  // We therefore parse the registry file text in a fail-closed way.
  //
  // Supported format (generated by Phase 3):
  //   const entries = [ ...JSON... ] as const;
  //   export default entries;
  const raw = await fs.readFile(registryFile, "utf8");
  const m = raw.match(/const\s+entries\s*=\s*(\[[\s\S]*?\])\s*as\s+const\s*;/);
  if (!m) {
    throw new Error(
      `Registry parse failed (expected 'const entries = [...] as const;'): ${registryFile}`,
    );
  }
  const arr = JSON.parse(m[1]!) as unknown;
  if (!Array.isArray(arr)) {
    throw new Error(`Registry parse failed (entries not array): ${registryFile}`);
  }
  const entries: RegistryEntry[] = [];
  for (const item of arr) {
    if (!item || typeof item !== "object") {
      throw new Error(`Invalid registry entry (not object) in ${registryFile}`);
    }
    const slug = (item as any).slug;
    const markdownPath = (item as any).markdownPath;
    if (typeof slug !== "string" || typeof markdownPath !== "string") {
      throw new Error(`Invalid registry entry shape in ${registryFile}`);
    }
    entries.push({ slug, markdownPath });
  }
  return entries;
}

export async function validateRegistryReferences(opts: {
  missingFrom: "phase1-approved";
}): Promise<void> {
  const phase1 = await findLatestApprovedRun(1);
  if (!phase1) {
    throw new Error("No approved Phase 1 run found; cannot validate registries.");
  }
  const missingReportPath = path.join(phase1.runDir, "missing_md_report.json");
  const missingReport = JSON.parse(await fs.readFile(missingReportPath, "utf8")) as {
    missing: string[];
  };
  const declaredMissing = new Set(missingReport.missing ?? []);

  const registryFiles = [
    path.join(CONTENT_REGISTRIES_ROOT, "components.config.ts"),
    path.join(CONTENT_REGISTRIES_ROOT, "foundations.config.ts"),
    path.join(CONTENT_REGISTRIES_ROOT, "writing.config.ts"),
  ];

  const failures: Array<{ registry: string; markdownPath: string; reason: string }> = [];

  for (const reg of registryFiles) {
    if (!(await fileExists(reg))) continue; // not present yet; Phase 1 will list as missing.
    const entries = await loadRegistryEntries(reg);
    for (const e of entries) {
      const mdRel = e.markdownPath.replaceAll("\\", "/");
      const mdAbs = path.join(process.cwd(), mdRel);
      const exists = await fileExists(mdAbs);
      if (exists) continue;
      // New invariant: fail if missing and not declared missing beforehand.
      if (!declaredMissing.has(mdRel)) {
        failures.push({
          registry: path.relative(process.cwd(), reg),
          markdownPath: mdRel,
          reason:
            "Registry references missing publishable markdown not declared in approved Phase 1 missing_md_report.json.",
        });
      }
    }
  }

  if (failures.length > 0) {
    const msg =
      "Registry validation failed:\n" +
      failures.map((f) => `- ${f.registry} -> ${f.markdownPath}: ${f.reason}`).join("\n");
    throw new Error(msg);
  }
}
